GET http://localhost:8080/task/get
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvcmcuc3ByaW5nZnJhbWV3b3JrLnNlY3VyaXR5LmNvcmUudXNlcmRldGFpbHMuVXNlciBbVXNlcm5hbWU9YWRtaW4sIFBhc3N3b3JkPVtQUk9URUNURURdLCBFbmFibGVkPXRydWUsIEFjY291bnROb25FeHBpcmVkPXRydWUsIENyZWRlbnRpYWxzTm9uRXhwaXJlZD10cnVlLCBBY2NvdW50Tm9uTG9ja2VkPXRydWUsIEdyYW50ZWQgQXV0aG9yaXRpZXM9W1JPTEVfQURNSU5dXSIsImlhdCI6MTc1MDkzMDQ5NywiZXhwIjoxNzUwOTY2NDk3fQ.u9JannlmLucML4gjRVYHp6KH0vDLSrI1c4Y5-_t25jQ
Accept: application/json

###

GET http://localhost:8080/task/get/3
Authorization: Bearer
Accept: application/json

###

POST http://localhost:8080/task/add
Authorization: Bearer
Content-Type: application/json

{
"taskName": "Create project",
  "date": "2025-08-22",
  "comp": false
}

###

DELETE http://localhost:8080/task/delete/2

###

PUT http://localhost:8080/task/update/1
Content-Type: application/json

{
  "taskName": "Create Spring Boot project",
  "date": "2025-06-22"
}

###

PUT http://localhost:8080/task/complete/3
Authorization: Bearer
Content-Type: application/json

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}