GET http://localhost:8080/task/get
Authorization: Bearer {{auth_token}}
Accept: application/json

###

GET http://localhost:8080/task/get/2
Authorization: Bearer {{auth_token}}
Accept: application/json

###

POST http://localhost:8080/task/add
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "taskName": "Create project",
  "date": "2025-08-22",
  "comp": false
}

###

DELETE http://localhost:8080/task/delete/3
Authorization: Bearer {{auth_token}}

###

PUT http://localhost:8080/task/update/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "taskName": "Create Spring Boot project",
  "date": "2025-06-22"
}

###

PUT http://localhost:8080/task/complete/202
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###

GET http://localhost:8080/task/get/name?taskName=Create Spring Boot project
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "Shivashish",
  "password": "Shiv@123"
}

> {% client.global.set("auth_token", response.body.token); %}

###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "Shivashish",
  "password": "Shiv@123",
  "role": "ADMIN"
}

> {% client.global.set("auth_token", response.body.token); %}

###

POST http://localhost:8080/auth/token-info
Authorization: Bearer {{auth_token}}
Content-Type: application/json


